version: '3'
services:
  rstudio:
    image: gslin1224/rstudio-chinese  
    container_name: rstudio_server_chinese            
    environment:
      - PASSWORD=password                             
      - LANG=zh_TW.UTF-8                           
      - LC_ALL=zh_TW.UTF-8
    ports:
      - "8787:8787"                              
    volumes:
      - ./project:/home/rstudio/project              
      - ./rstudio_library:/usr/local/lib/R/site-library  
    restart: unless-stopped                         

