version: '3'
services:
  rstudio:
    image: rocker/rstudio:latest  
    container_name: rstudio_server_chinese
    environment:
      - PASSWORD=password         
      - LANG=zh_TW.UTF-8          
      - LC_ALL=zh_TW.UTF-8
    ports:
      - "8787:8787"              
    volumes:
      - ./:/home/rstudio/project  
      - ./rstudio_library:/usr/local/lib/R/site-library  
    restart: unless-stopped     
    command: >
      bash -c "apt-get update &&
               apt-get install -y locales fonts-noto-cjk &&
               locale-gen zh_TW.UTF-8 &&
               /init"
